import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

public class KonversiSuhuFrame extends javax.swing.JFrame {

    /** Creates new form KonversiSuhuFrame */
    public KonversiSuhuFrame() {
        initComponents();
        setupDocumentListener();
    }
    private void setupDocumentListener(){    
    inputSuhu.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    @Override
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        btnKonversiActionPerformed();
    }
    
    @Override
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        btnKonversiActionPerformed();
    }
    
    @Override
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        btnKonversiActionPerformed();
    }
    private void btnKonversiActionPerformed(){
    }
    });
    }

private double celsiusToFahrenheit(double celsius) {
    return (celsius * 9/5) + 32;
}

private double celsiusToReamur(double celsius) {
    return celsius * 4/5;
}

private double celsiusToKelvin(double celsius) {
    return celsius + 273.15;
}
// Dari Fahrenheit ke skala lain
private double fahrenheitToCelsius(double fahrenheit) {
    return (fahrenheit - 32) * 5/9;
}

private double fahrenheitToReamur(double fahrenheit) {
    return (fahrenheit - 32) * 4/9;
}

private double fahrenheitToKelvin(double fahrenheit) {
    return (fahrenheit - 32) * 5/9 + 273.15;
} 

// Dari Kelvin
private double kelvinToCelsius(double kelvin) {
    return kelvin - 273.15;
}

private double kelvinToFahrenheit(double kelvin) {
    return (kelvin - 273.15) * 9/5 + 32;
}

private double kelvinToReamur(double kelvin) {
    return (kelvin - 273.15) * 4/5;
}
    
// Dari Reamur
private double reamurToCelsius(double reamur) {
    return reamur * 5/4;
}

private double reamurToFahrenheit(double reamur) {
    return reamur * 9/4 + 32;
}

private double reamurToKelvin(double reamur) {
    return reamur * 5/4 + 273.15;
}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelHasil = new javax.swing.JLabel();
        inputSuhu = new javax.swing.JTextField();
        jenisKonversi = new javax.swing.JComboBox<>();
        btnKonversi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Celsius = new javax.swing.JRadioButton();
        Fahrenheit = new javax.swing.JRadioButton();
        Reamur = new javax.swing.JRadioButton();
        Kelvin = new javax.swing.JRadioButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Konversi Suhu");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Masukkan Nilai Suhu");

        labelHasil.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        labelHasil.setText("Hasil");

        inputSuhu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        inputSuhu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputSuhuFocusGained(evt);
            }
        });
        inputSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputSuhuKeyTyped(evt);
            }
        });

        jenisKonversi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnKonversi.setBackground(new java.awt.Color(102, 255, 204));
        btnKonversi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("Aplikasi Konversi Suhu");

        buttonGroup1.add(Celsius);
        Celsius.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Celsius.setText("Celsius");
        Celsius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CelsiusItemStateChanged(evt);
            }
        });

        buttonGroup1.add(Fahrenheit);
        Fahrenheit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fahrenheit.setText("Fahrenheit");
        Fahrenheit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FahrenheitItemStateChanged(evt);
            }
        });

        buttonGroup1.add(Reamur);
        Reamur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reamur.setText("Reamur");
        Reamur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReamurItemStateChanged(evt);
            }
        });

        buttonGroup1.add(Kelvin);
        Kelvin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kelvin.setText("Kelvin");
        Kelvin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KelvinItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(btnKonversi))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(461, 461, 461)
                            .addComponent(labelHasil)
                            .addGap(114, 114, 114))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Celsius, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Fahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(Reamur, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Kelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(83, 83, 83)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jenisKonversi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fahrenheit)
                    .addComponent(Celsius)
                    .addComponent(Reamur)
                    .addComponent(Kelvin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jenisKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnKonversi)
                .addGap(1, 1, 1)
                .addComponent(labelHasil)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
    try {    
            double inputsuhu = Double.parseDouble(inputSuhu.getText());
            String hasilKonversi = (String) jenisKonversi.getSelectedItem();
            double hasil = 0.0;

        // Periksa arah konversi berdasarkan pilihan JRadioButton
        if (Celsius.isSelected()) {
            // Konversi dari Celsius ke skala yang dipilih
            switch (hasilKonversi) {
                case "Celsius ke Fahrenheit":
                    hasil = celsiusToFahrenheit(inputsuhu);
                    break;
                case "Celsius ke Kelvin":
                    hasil = celsiusToKelvin(inputsuhu);
                    break;
                case "Celsius ke Reamur":
                    hasil = celsiusToReamur(inputsuhu);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Pilihan konversi tidak valid!");
                    break;
                    
            }
        } else if (Fahrenheit.isSelected()) {
            // Konversi dari Fahrenheit ke skala yang dipilih
            switch (hasilKonversi) {
                case "Fahrenheit ke Celsius":
                    hasil = fahrenheitToCelsius(inputsuhu);
                    break;
                case "Fahrenheit ke Kelvin":
                    hasil = fahrenheitToKelvin(inputsuhu);
                    break;
                case "Fahrenheit ke Reamur":
                    hasil = fahrenheitToReamur(inputsuhu);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Pilihan konversi tidak valid!");
                    break;    
            }
        
        } else if (Reamur.isSelected()) {
            switch (hasilKonversi) {
                case "Reamur ke Celsius":
                    hasil = reamurToCelsius(inputsuhu);
                    break;
                case "Reamur ke Fahrenheit":
                    hasil = reamurToFahrenheit(inputsuhu);
                    break;
                case "Reamur ke Kelvin":
                    hasil = reamurToKelvin(inputsuhu);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Pilihan konversi tidak valid!");
                    break;
                }
            } else if (Kelvin.isSelected()) {
            switch (hasilKonversi) {
                case "Kelvin ke Celsius":
                    hasil = kelvinToCelsius(inputsuhu);
                    break;
                case "Kelvin ke Fahrenheit":
                    hasil = kelvinToFahrenheit(inputsuhu);
                    break;
                case "Kelvin ke Reamur":
                    hasil = kelvinToReamur(inputsuhu);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Pilihan konversi tidak valid!");
                    break;
            }
            }
        

         labelHasil.setText("" + hasil);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
        }                                               
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void inputSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSuhuKeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '.') {
        evt.consume();
    }// TODO add your handling code here:
    }//GEN-LAST:event_inputSuhuKeyTyped

    private void CelsiusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CelsiusItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
            jenisKonversi.removeAllItems();
            jenisKonversi.addItem("Celsius ke Fahrenheit");
            jenisKonversi.addItem("Celsius ke Kelvin");
            jenisKonversi.addItem("Celsius ke Reamur");
        }    
    }//GEN-LAST:event_CelsiusItemStateChanged

    private void FahrenheitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FahrenheitItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
            jenisKonversi.removeAllItems();
            jenisKonversi.addItem("Fahrenheit ke Celsius");
            jenisKonversi.addItem("Fahrenheit ke Kelvin");
            jenisKonversi.addItem("Fahrenheit ke Reamur");        
    }//GEN-LAST:event_FahrenheitItemStateChanged
    }
    private void ReamurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReamurItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
            jenisKonversi.removeAllItems();
            jenisKonversi.addItem("Reamur ke Celsius");
            jenisKonversi.addItem("Reamur ke Fahrenheit");
            jenisKonversi.addItem("Reamur ke Kelvin");
        }
    }//GEN-LAST:event_ReamurItemStateChanged

    private void KelvinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KelvinItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
            jenisKonversi.removeAllItems();
            jenisKonversi.addItem("Kelvin ke Celsius");
            jenisKonversi.addItem("Kelvin ke Fahrenheit");
            jenisKonversi.addItem("Kelvin ke Reamur");
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_KelvinItemStateChanged

    private void inputSuhuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSuhuFocusGained
    inputSuhu.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_inputSuhuFocusGained
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuFrame().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Celsius;
    private javax.swing.JRadioButton Fahrenheit;
    private javax.swing.JRadioButton Kelvin;
    private javax.swing.JRadioButton Reamur;
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenisKonversi;
    private javax.swing.JLabel labelHasil;
    // End of variables declaration//GEN-END:variables


}
